### ISSUE TITLE
Not work on Android 6

### ISSUE THREAD

**Issue by robertle2812** [mugku/Android-LockScreenSample-DisableHomeButtonKey#2]
Lock screen not show on Android 6.

**Comment by mugku** [comment]
Hi~ robertle2812 ~ 

Ok. Thanks~ I will check it...ASAP...

Best Regards

**Comment by robertle2812** [comment]
Thanks a lot mugku.
Best regards.

**Comment by bru22** [comment]
Hi~ mugku
I've found the same issue.
The project I set "targetSdkVersion 23" on build.gradle,
then I start LockscreenService() ,and app crashed.
Thank you ,
bru22

**Comment by mugku** [comment]
Hi~ I updated new version
Check PLZ. 

Thanks
