### ISSUE TITLE
Cannot resolve symbol 'ContextInstance'

### ISSUE THREAD

**Issue by kahyalar** [mugku/Android-LockScreenSample-DisableHomeButtonKey#3]
Hello, 
First of all thanks for that package. It might be really useful.

I get an error, which i write on to title. I add gradle dependecies and call the function : Lockscreen.getInstance(ContextInstance).startLockscreenService();

I hope, you'll find out why.
Happy coding

**Comment by mugku** [comment]
Hi~ I updated new version
Check PLZ. 

Thanks
