### ISSUE TITLE
Error:Exception thrown while executing model rule: org.gradle.api.publish.plugins.PublishingPlugin$Rules#addConfiguredPublicationsToProjectPublicationRegistry(org.gradle.api.internal.artifacts.ivyservice.projectmodule.ProjectPublicationRegistry, org.gradle.api.publish.PublishingExtension, org.gradle.api.internal.project.ProjectIdentifier)

### ISSUE THREAD

**Issue by zhhaohp** [mugku/Android-LockScreenSample-DisableHomeButtonKey#4]
Error:Exception thrown while executing model rule: org.gradle.api.publish.plugins.PublishingPlugin$Rules#addConfiguredPublicationsToProjectPublicationRegistry(org.gradle.api.internal.artifacts.ivyservice.projectmodule.ProjectPublicationRegistry, org.gradle.api.publish.PublishingExtension, org.gradle.api.internal.project.ProjectIdentifier)

What can I do?

**Comment by mugku** [comment]
you just delete apply plugin: 'com.novoda.bintray-release' at build.gradle in lockscreenusingservice project.

and I updated new version 
this version adapted over Android M
