### ISSUE TITLE
build error，help me

### ISSUE THREAD

**Issue by zhhaohp** [mugku/Android-LockScreenSample-DisableHomeButtonKey#5]
it's work now

**Comment by zhhaohp** [comment]
that‘s ok now.

**Comment by mugku** [comment]
Hi~

Are you OK? 

I close this issue(https://github.com/mugku/Android-LockScreenSample-DisableHomeButtonKey/issues/4)

**Comment by zhhaohp** [comment]
that's ok, thanks.
