### ISSUE TITLE
在小米手机上没用

### ISSUE THREAD

**Issue by nonstoplm** [mugku/Android-LockScreenSample-DisableHomeButtonKey#6]
你好，在小米手机上，亮屏后无法出现自定义lockscreen，要在解锁后，才能看到自定义lockscreen。请问能实现类似网易云音乐的效果吗？即点亮屏幕后，即能看到自定义的LockScreen。(不是音乐播放的RemoteControlClient那种)  谢谢！

**Comment by mugku** [comment]
Hi~ nonstoplm

Unfortunately, I can not understand Chinese.
Please Write Korean or English

Thanks :)

**Comment by zhhaohp** [comment]
He‘s means：it can't work wonderful at MIUI，the custom lockscreen is under system lockscreen when SCREEN_ON

**Comment by mugku** [comment]
Hi~ nonstoplm , zhhaohp

Thanks @zhhaohp translate chinese to english~ 👍  :)

And .... @nonstoplm ~~
Unfortunately, I don't have a phone MIUI.
Is your phone Xiaomi? 

Thans :)
