### ISSUE TITLE
Notification drawer

### ISSUE THREAD

**Issue by KiOskars** [mugku/Android-LockScreenSample-DisableHomeButtonKey#8]
Hi @DUBULEE

I've tried to impleemnt so that the status bar is shown in the lockscreen and that you can pull down the notification drawer. I've managed to get both by commenting out mParams.flags = WindowManager.LayoutParams.FLAG_DRAWS_SYSTEM_BAR_BACKGROUNDS;

The problem now is that the drawer goes behind the lock screeen... Do you have any idea on how to solve this? Without making your custom notification manager appear on screen.

And for last, 
thanks, It's a great project!

**Comment by mugku** [comment]
Hi @KiOskars 

Do you want the system notification screen to above the lockscreen?

That's possible. If the system is not locked. 
However, it is impossible if there is a system lock.
I have no idea.

If PIN, Pattern Lock is needed, it is necessary to implement it directly.

Sorry for not helping you.

Thanks.
